---
title: "Constitution"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center><font size="3">
**Constitution of the Statistics Graduate Student Union**  
Date of Ratification: September 16, 2022

</font></center>

1.  **Name:** Statistics Graduate Student Union, hereafter known as the Union.

2.  **Purpose:** The purpose of the Union shall be:

    -   to add community to the graduate students of the Department;

    -   to act as a liaison with the staff for discussions, planning and general communication with them;

    -   to advocate for members of the Union;

    -   to keep graduate students informed about events in the Department both intra- and extra-curricular, particularly when they are directly concerned;

    -   to get to know other students better and to promote dialogue between them;

    -   to assist in planning social, academic, and other events in the Department; and

    -   to participate in and encourage any activities which will further these aims.

3.  **Membership:** All full and part-time PhD and MSc students registered in the department shall be members of the Union.

4.  **Executive:** The executive committee of the Union shall be composed of a President and Treasurer. These positions are to be held by distinct members of the Union. Additional members may hold titles such as Secretary, Social Coordinator, First-Year Representative, Masters’ Students Representative, Vice-President Internal, or Vice-President.

    The executive shall meet as required. A majority of the executive shall constitute a quorum.

5.  **Elections:** All members who will be at the University for their term of office are eligible to be members of the executive. The election for President shall be held each fall (excluding 2022) in the second half of September after a nomination period in the first two weeks of September, for a one-year term. The election will take place electronically. In the event of an uncontested election, the election will be a confidence vote and the voter will have the choice between *Yes*, *No*, and *Abstain*. In all instances, a plurality of voting members will constitute a confirmation of position. In the event of a non-confirmation in a confidence vote, an election will be run within two weeks of the original election with a new candidate after a call for nominations. It is the obligation of the President to communicate the nomination and election process.

    The President should fill all other positions on the executive by the end of October. The President shall call an election for these roles should multiple candidates be interested; however, the President should also seek to accommodate candidates by suggesting alternate roles should multiple candidates seek the same role. The call for nominations for all executive officers shall be sent via email to every member in attendance.

6.  **General Meetings:** In the event a general meeting is required the executive committee will call a meeting with fourteen days notice to Union members. Five percent of non-executive Union members shall constitute a quorum for a general meeting, rounded down to the nearest whole number if necessary. A general meeting may be called at any time by request of the President, or upon petition by one third of the executive, or upon petition by fifteen percent of the members of the Union. Every general meeting and its agenda must be publicly announced seven days prior to the meeting. The secretary must take minutes of any general meeting. Should the secretary be unable to attend the meeting, or should the position be vacant, another executive member must take minutes in their stead.

7.  **Recalls:** Executive officers may be recalled by a two-thirds vote at any general meeting or by a two-thirds vote at an executive committee meeting. The majority of executives must attend a meeting where a recall is taking place. Should any executive be unable to serve their term in full, or become unreachable by email for more than three weeks without explanation, their position will be declared vacant. In the event that the role of President becomes vacant, a by-election will be held. In the event that other executive roles are vacant, the President will nominate a replacement.

8.  **Financial Responsibility:** Any funds held by the Union shall be deposited in an official account in the name of the Union and shall be the responsibility of the President and Treasurer. Members may not contract debts on behalf of the Union. A written record must be made by the Treasurer and President prior to any monetary transfers.

9.  **Record Keeping:** The President is responsible for storing passwords to the Union’s electronic accounts (including, but not limited to, email, GitHub, cloud storage) and providing them to executive officers as necessary and the next President.

    All executive officers shall complete an exit report at the end of their term describing their work during their term and suggesting changes if necessary for their successor. These reports shall be stored for at least ten years electronically on a drive accessible to executive officers of the Union.

    Additionally, executives will make a single report available to all members of the Union describing their term as an executive at the end of their term. These reports will be available for two years.

    The President, Secretary (if non-vacant), and Vice-President Internal (if non-vacant) shall be responsible for submitting the required documentation to the UTGSU to remain in compliance with their by-laws and policies. In particular, the President should ensure that the constitution, financial statement, budget, minutes of any general meetings, and an activities report are submitted to the UTGSU in accordance with clause 01.12.9 of the UTGSU Policy Handbook.

10. **Amendment of the Constitution:** This constitution may be amended at any general meeting by a two-thirds majority vote of those present at the meeting. Proposed amendments must be announced at least one week before the general meeting.
