---
title: "People"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 2025-26 Team
President: Luis Sierra Muntané \
Treasurer: Bernard Miskic \
Vice-President, Internal: Elijah French \
Vice-President, Events: Leo Watson \
Vice-President, Academic: Vinky Wang \
Secretary: Luis Sierra Muntané \
First Year Representative: Pat Chimtanoo \
MSc Representative: Mahdi Zamani \

<br>

## Past teams
### 2024-25 Team
President: Konstantinos Christopher Tsiolis \
Vice-President, Internal: Elijah French \
Vice-President, Academic: Mandy Yao \
Vice-President, Events: Bernard Miskic \
Secretary: Luis Sierra Muntané \
Treasurer: Pak Hop Chan \
First Year Representative: Leo Watson \
MSc Representative: Bushra Haque \

### 2023-24 Team
President: Mandy Yao \
Vice-President: Yovna Junglee \
Vice-President, Events: Marco Antonio Gallegos Herrada \
Secretary: Pak Hop Chan \
Treasurer: Kathleen Miao \
Academic Liaison: Konstantinos Christopher Tsiolis \
First Year Representative: Maggie Zhai \
MSc Representative: Bernard Miskic \

### 2022-23 Team
President: Liam Welsh \
Vice-President: Emily Somerset \
Vice-President, Internal: Kathleen Miao \
Secretary: Morris Greenberg \
Treasurer: Emma Kroell \
Academic Liaison: Vedant Choudhary \
First Year Representative: Mandy Yao \
MSc Representative: Alexander Valencia \

### 2021-22 Team
President: Emma Kroell \
Treasurer: Madhu Gunasingam \
First Year Representative: Kathleen Miao \
MSc Representatives: Lindsay Katz and Kristine Villaluna \




